name = "orienteer-live-api"
main = "src/index.js"
compatibility_date = "2026-06-01"

[vars]
ADMIN_PASSWORD = "admin123"

[[durable_objects.bindings]]
name = "EVENT_ROOM"
class_name = "EventRoom"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["EventRoom"]
